### ISSUE TITLE
Recipe folder

### ISSUE THREAD

**Issue by Inverseder** [CompactMods/CompactCrafting#10]
Hey,
I'm a modpack maker and I want to create some new recipes with your mod but i didn't find the folder or document to make the recipe when i installing the mod. Can you help me please?
Thanks for your answer

**Comment by robotgryphon** [comment]
Hey!

You can find most of the recipe specification on the Wiki section of this repository, [here](https://github.com/CompactMods/CompactCrafting/wiki/Recipe-Specification). The wiki goes over the available layer types and what each part of the JSON files the recipe loader expects. After that, it's just dropping the recipe files into a valid datapack under `//PACK/data/recipes/DOMAIN/file.json` (the same as any other recipe in vanilla datapacks).

If you run into any issues, feel free to join the [Compact Mods Discord](https://discord.gg/gzskZVTc55) to ask questions there, as well.
