### ISSUE TITLE
Feild Projector not dropping

### ISSUE THREAD

**Issue by PrincessStrelka** [CompactMods/CompactCrafting#11]
The Feild Projector does not drop when mined in survival. I tried with all pickaxe levels and silk touch and it would not drop an item when broken. Tested in 1.0.0 alpha 2

**Comment by Mendanbar** [comment]
I'm seeing the same in Enigmatica 6 v0.4.0.  It also includes 1.0.0 alpha 2.

**Comment by robotgryphon** [comment]
Looks like despite the loot tables being generated, they didn't get pulled into the final mod jar. My bad! I've made a temporary datapack here to solve this in alpha 1 and alpha 2; I'll get a permanent fix into alpha 3 in the near future.

Simply download and unzip this into your world's `datapacks` folder, and it should solve the issue: [fix-drops.zip](https://github.com/CompactMods/CompactCrafting/files/6048280/fix-drops.zip)

**Comment by robotgryphon** [comment]
This should now be solved in beta 1. Grab it from releases or CurseForge.
