### ISSUE TITLE
Wiki Feature

### ISSUE THREAD

**Issue by 5t3v3n** [CompactMods/CompactCrafting#17]
Possibly a working recipe example? even just all vanilla ingredients and output but using all 3 types of layers.

This would be very appreciated

Cheers

**Comment by SizableShrimp** [comment]
Hi, in future versions, there will be a command to automatically generate recipes based on blocks in a field. We can work on fixing up the wiki as well. Please join our Discord for further support for now (see README).

**Comment by robotgryphon** [comment]
You can find an example [here](https://github.com/CompactMods/CompactCrafting/blob/1.16.x/recipes/diamond_block.json) which shows a vanilla recipe to duplicate diamond blocks. For more information, the wiki has information on various parts of the recipe specification, or you can join the Discord which Shrimp mentioned above.
