### ISSUE TITLE
Unable to connect to server (io.netty.handler.codec.EncoderException)

### ISSUE THREAD

**Issue by zpprsprk** [CompactMods/CompactCrafting#18]
Upon connecting to a server with compactcrafting-1.0.0-beta.1.jar (or ...-beta.2.jar) the following message appears in the server log as well as on screen for the client.
[23:43:39] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: ZpprSprk lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
This seems to be a regression in 1.0.0-alpha.2..1.0.0-beta.1 as connecting to the server works fine for the alpha.2 version.

It does seem to function as intended when it is the only mod in the game, but adding in the rest of the mods in my modpack in development does expose the issue.

Modlist:
https://gist.github.com/zpprsprk/6b1dbc33c7d35d6b9cd023846fdd6f66

manifest.json file (for specific fileIDs for each mod)
https://gist.github.com/zpprsprk/f03aba7902a233bb334363c0a0bb3e3c

**Comment by SizableShrimp** [comment]
Please put the the manifest in a gist or something instead of pasting it here. Also, can you please provide your debug.log?

**Comment by NielsPilgaard** [comment]
I've been struggling with finding the culprit of this bug for many days now, and at long last confirmed that removing my custom Compact Machine recipes allowed me to once again join servers.

Edit: Here's the KubeJS script that made the CM recipes: https://gist.github.com/NillerMedDild/3b074d58d9d9ad0df483a199eba581cd

**Comment by robotgryphon** [comment]
Still need a debug log for this issue. Looking through the diff between versions isn't bringing anything obvious up.

**Comment by NielsPilgaard** [comment]
client latest log: <https://gist.github.com/NillerMedDild/31ccbe932a3891d5742f34c4a745e396>
server latest log: <https://gist.github.com/NillerMedDild/317f65f810cafb35f8b72d6dc109cd44>
server debug log: <https://gist.github.com/NillerMedDild/cd3734d2db798b8909da9fdf18103d5a>
server kubejs server.txt: <https://gist.github.com/NillerMedDild/166f3e7aac956d2a92edcf443e1ad13f>

**Comment by robotgryphon** [comment]
We will be publishing a new version shortly that has several bugfixes; if you would like early access to it for validation, please join the Discord here: https://discord.gg/QN9MQHku (expires after the beta goes public)

If this is still an issue, please try to cut down the number of potential mods in the list. I can't build a dev environment with 200+ mods. Thanks.
