### ISSUE TITLE
[Request] Tile Entities with NBT in recipes

### ISSUE THREAD

**Issue by aaronhowser1** [CompactMods/CompactCrafting#31]
I saw this:
```json
{
    "type": "compactcrafting:block",
    "block": "minecraft:block_id_here",
    "properties": {
        "{property}": ["accepted", "values", "here"]
    }
}
```
but im not really sure what it means by property. I tried this:
```json
            "P": {
              "type": "compactcrafting:block",
              "block": "botania:mana_pool",
              "properties": {
                "mana": 1000000
              }
            }
```
but it works with mana pools that don't have any mana in them. Replacing `"mana"` with `"{mana}"` also doesn't work.

**Comment by SizableShrimp** [comment]
They're blockstate properties. You need to use the property ids and their allowed values. If you're having a hard time making these by hand, you can use a dev build with helper commands to do so. See the Compact Mods discord in the README. But also you should be able to see the right names for the blockstate properties in F3 when looking at the block.

**Comment by aaronhowser1** [comment]
So, no there isn't a way to use NBT? Just blockstates?

**Comment by SizableShrimp** [comment]
I don't think blocks can hold NBT, do you mean tile entities?

**Comment by aaronhowser1** [comment]
Yes, sorry that's what I meant. I forgot those weren't technically the same thing.

My example *is* trying to combine 27 full mana pools, though.

**Comment by SizableShrimp** [comment]
Matching tile entities nor their NBT isn't supported at the moment. So, no, you can't do that.

**Comment by robotgryphon** [comment]
So, I would like to support this (likely with the `data` name for the JSON group) but unfortunately due to how CC currently scans on block updates, this is tricky.

I'll probably be deferring this until proxy blocks are done, so you can do manual recipe scans with redstone signals. The actual data can be matched by dumping tile NBT via `save` on the server side.
