### ISSUE TITLE
CompactCrafting spamming debug log

### ISSUE THREAD

**Issue by Lachim3** [CompactMods/CompactCrafting#32]
[debug.log](https://github.com/CompactMods/CompactCrafting/files/6732655/debug.log)

**Comment by robotgryphon** [comment]
- scratch that -

I will be eliminating this logging in the next release. It was added to troubleshoot recipes not getting matched and was left in by mistake. Sorry about that.

**Comment by robotgryphon** [comment]
This is now solved in the latest nightly builds. A server configuration file is created that has settings for toggling the additional logging.

![image](https://user-images.githubusercontent.com/8529636/125158976-714e9a80-e142-11eb-987e-531dfe2046e2.png)

`fieldBlockChanges` is the one that turns on the nearby projector logging, as well as when a field is scanning for updated blocks.
