### ISSUE TITLE
Redstone Dust/Other Non-Full Blocks

### ISSUE THREAD

**Issue by CyberFinn69** [CompactMods/CompactCrafting#34]
I've tried this:
```
	"components": {
		"R": {
			"type": "compactcrafting:block",
			"block": "minecraft:redstone"
		},
		"I": {
			"type":"compactcrafting:block",
			"block": "minecraft:iron_block"
		}
		},
```
And it doesn't work because of the redstone.
Does there need to be something else than ```"compactcrafting:block"```?
Please help.

**Comment by robotgryphon** [comment]
I believe you want `redstone_wire`, not `redstone` there. `redstone` is the item form. You can always use F3 mode to check names and property values.

![image](https://user-images.githubusercontent.com/8529636/126683985-926ae162-10cb-4d62-abad-32eb75c445c2.png)

(FYI - There is an extra `properties` group that you can add for specific whitelisting of properties. There's an example under the [tests for the block component](https://github.com/CompactMods/CompactCrafting/blob/1.16.x/src/test/resources/components/block/block_properties.json).

**Comment by robotgryphon** [comment]
Closing this as stale for lack of response; please comment if this is still an issue. Thanks!
