### ISSUE TITLE
[Suggestion] Possibility to placed the projector facing the other way

### ISSUE THREAD

**Issue by Fireztonez** [CompactMods/CompactCrafting#37]
Right now when you placed the projector, it always face the way you looking at. I would like to have a way to placed the projector the other way.

Why?
Right now you always have to be in the back of the projector to be able to place corectly the projector facing the good way. If you are on a close room, you will have to mine a hole in the wall, to go in the back question to place it right. And at the end, it take a bit more time even if you are on a open space, because you have to go little ferther in each dirrection, to place the projectors...

How can this be done in the mod?
There have multiples way you can do that, I think this can be the new default way to place directly without any issue, but this can be done like multiples other mods does, by a Shift Right-click question to invert the placement way.

Version: 1.0.0 Beta 3
Minecraft: 1.16.5
Forge: 36.2.1

**Comment by robotgryphon** [comment]
Already in place for the next release, per this commit: 4928b4598776a78beb140ed6021cfc54d687de5c

It'll be activated when you hold shift, per the suggestion.
