### ISSUE TITLE
[Suggestion] Added a way to turn off the field projector with redtsone signal

### ISSUE THREAD

**Issue by Fireztonez** [CompactMods/CompactCrafting#38]
I would like to have a way to turn off the FIeld Projector by giving a redstone signal to one of the projectors, question to stop the Projector Field to show, when it is not needed and stop the verifications of blocks inside the field.

I think this whold be great to stop the innutiles overlay rendering (Who can be a bit anoying when not needed) and stop block scan, who can possibly be eavy server side when is not needed at all (I didn't make a profile or anything yet, but for what I remember in 1.12.2 with CompactMachine craftin, each projector took a bit much resources when not used, when looking with Lag Goggles on it).

Version: 1.0.0 Beta 3
Minecraft: 1.16.5
Forge: 36.2.1

**Comment by robotgryphon** [comment]
The good news is that CM4 has rewritten scanning code so none of the projectors tick anymore. That should improve performance a bit.

As for the field overlay, I can see about squeezing that in with the other visual improvements coming in the next beta. Seems small enough.

**Comment by Fireztonez** [comment]
Ok, for the performance this is a good thing to know,
For the visual improvement I'm curious to see what it will look like. And if you have redstone signal to turn it of this will be amazing.

Thank's for your great work!

**Comment by robotgryphon** [comment]
Closed with commit 6b97fd1df45ead594a6f79a1ba0bbb8833a86d3d; tested on both single and multiplayer. Will be included in the next beta.
