### ISSUE TITLE
Some problems on the server

### ISSUE THREAD

**Issue by xianyujunshigeCDD** [CompactMods/CompactCrafting#39]
My English is not good, so I use translation software

I added your module and configured the data package in the loliserver of 1.16, but the data package that can take effect in the single file has not been successfully loaded in the server. Is there any solution? Is it related to the server

**Comment by robotgryphon** [comment]
I'm afraid I don't quite understand. You can either type your inquiry in your native language and I can see about delegating the request, or you can always feel free to join the Compact Mods Discord in order to discuss this more: https://discord.gg/abca3pDPvu

Thanks!

**Comment by robotgryphon** [comment]
Closing this for non-response in two months.
