### ISSUE TITLE
3x3x3 and 5x5x5 recipes can't be done on 7x7x7 field

### ISSUE THREAD

**Issue by Fireztonez** [CompactMods/CompactCrafting#40]
In my test world, I try to make a recipes made for smaller field on a 7x7x7 field and doesn't work. I have tried both a really simple recipe for making the wall block, made to work on a 3x3x3 field, and a recipe for a comapct machine make for being made on a 5x5x5 field. Both doesn't work. I tried both recipes on is respective field size and the comapct wall recipe on the 5x5x5 and everithing work great for those.

To make sure it is not because I missed place a block on the recipe for the compact machine I used the Copy-Paste gadget, to copy from my 7x7x7 field to the 5x5x5, break and placed back a block (Question that the field projector correctly detects the blocks), drop the catalyst and the compacting start directly.

Versions:
CompactCrafting: 1.0.0 Beta 3
Minecraft: 1.16.5
Forge: 36.2.1

**Comment by robotgryphon** [comment]
Should now be closed as of beta 5; if this is still an issue, please reopen.
