### ISSUE TITLE
Some recipes don't work unless you break and replace the Projector

### ISSUE THREAD

**Issue by aaronhowser1** [CompactMods/CompactCrafting#42]
https://www.youtube.com/watch?v=4RUvnEbN4j4

This is on FTB University 1.16, which has `compactcrafting-1.0.0-beta.3`

**Comment by nicolaspaillard** [comment]
Same issue on Ragnamod VI with compactcrafting-1.0.0-beta.3 so we can't automate

**Comment by robotgryphon** [comment]
Please let me know if this is still an issue with beta 5/6. Those versions have additional toggles for more logging, which can help track this down.

**Comment by robotgryphon** [comment]
Can no longer reproduce this in the latest code. Closing as it will be solved in beta 8.
