### ISSUE TITLE
Compact Crafting crash with AE2 and other mods

### ISSUE THREAD

**Issue by jeremiahwinsley** [CompactMods/CompactCrafting#45]
Modpack: ATM-6 1.8.7
CC version: 1.0.0-beta.6

The field registration code crashes with other mods that store data in the world. I'm not sure how to replicate the crash, but here are crash logs from two different instances:

https://gist.github.com/jeremiahwinsley/487a9c03ec193e082d0c07daf523067f

https://gist.github.com/kaoticgam3rs/69e9bb379130368acd0097f10150f90c

**Comment by gregoriousbig** [comment]
I've also had this issue and had to disable the mod to be able to join my world again.

https://gist.github.com/gregoriousbig/653434e2df8ab0af3009dbeaae217ba5
