### ISSUE TITLE
Crafting machines

### ISSUE THREAD

**Issue by lullbull** [CompactMods/CompactCrafting#46]
I cant craft any machines except walls and projectors. I have tried the suggested fixes and in several worlds but its not working in any of them.

**Comment by robotgryphon** [comment]
Please retry with the latest Compact Crafting beta (7), as recipes have had several iterations of tests and fixes applied to them.

**Comment by robotgryphon** [comment]
Closing as stale. If this is still an issue, feel free to comment or join our Discord for troubleshooting.
