### ISSUE TITLE
Issue with KubeJS and Multiplayer

### ISSUE THREAD

**Issue by robotgryphon** [CompactMods/CompactCrafting#49]
Issue appears related to replacing a mod recipe with a CC recipe using KubeJS. See attached KubeJS script and screenshot.

Script: [infusion_altar.txt](https://github.com/CompactMods/CompactCrafting/files/7710446/infusion_altar.txt)

Mod Versions:
![unknown](https://user-images.githubusercontent.com/8529636/145973705-b6934247-3d54-44b9-92b5-8d0295d2bfc9.png)

**Comment by fireheart3911** [comment]
Maybe add Mystical Agriculture to your modpack....
