### ISSUE TITLE
not craftable

### ISSUE THREAD

**Issue by VIV1X** [CompactMods/CompactCrafting#50]
I am on 1.16.5 and the tunnels are not craftable but also I cant get the recipe to show in jei

**Comment by Apceniy** [comment]
Tunnels don't work in 1.16.5, that's why. The mod author is about to release them for 1.18.1

**Comment by VIV1X** [comment]
ah ok thanks for the reply, what about the recipe problem can you help me with this?

**Comment by Apceniy** [comment]
they don't have a recipe because you're not supposed to get them in survival mode **because they don't work**, duh

**Comment by VIV1X** [comment]
maybe I could of been a little more clear, I cant get any recipe for compact crafting

**Comment by Apceniy** [comment]
which recipe for which item you're expecting?

**Comment by VIV1X** [comment]
compact crafting is just not working, it has no recipes in jei but I also tried a recipe I know is a recipe and it didn't craft it.

**Comment by Apceniy** [comment]
>  I also tried a recipe I know is a recipe and it didn't craft it.

Can you please be more specific about that? Not just "I tried a recipe" but which one you tried. It's hard to help without knowing exactly what are you trying to do

**Comment by robotgryphon** [comment]
Closing this for lack of clarification and it going stale. Please reach out on Discord or reopen if you need more assistance, thanks!
