### ISSUE TITLE
No crafting recipies for Compact machines

### ISSUE THREAD

**Issue by number947** [CompactMods/CompactCrafting#52]
When i disable vanilla recipies for Compact Machines, i cannot see their Compact Crafting recipies anymore or craft them in any way (i tried using old recipe from CM3 and that didn't work). Do i have to add recipies manually to CC or they are integrated in CM/CC and i do something wrong? If it is the former i'm quite ok with that, but i would want to know it before i mess something up.

My Minecraft version is 1.16.5
Forge: 36.2.22
Compact Machines: 4.0.0-beta.2
Compact Crafting: 1.0.0
JEI: 7.7.1.150

**Comment by Apceniy** [comment]
These mods don't contain integration by themselves, but it can be added manually, for example with this datapack: https://github.com/CompactMods/compact-recipes

**Comment by number947** [comment]
> These mods don't contain integration by themselves, but it can be added manually, for example with this datapack: https://github.com/CompactMods/compact-recipes

Thank you! It worked out! Now i've got all the recipies. (Except for tunnels but they're not working anyway)
