### ISSUE TITLE
Error with empty corner block

### ISSUE THREAD

**Issue by LindaJuffermans** [CompactMods/CompactCrafting#58]
PFA a KubeJS script for CompactCrafting.
[miniaturization.txt](https://github.com/CompactMods/CompactCrafting/files/8646844/miniaturization.txt)

No issues in singleplayer,

When a player tries to connect to a server, they get kicked and the log has this error:
```
[08May2022 09:54:09.402] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: LynMimistrobell joined the game
[08May2022 09:54:24.278] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: LynMimistrobell lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ArrayIndexOutOfBoundsException: 5
[08May2022 09:54:24.279] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: LynMimistrobell left the game
```

The workaround was to add block `G` as `minecraft:air` and replace the first `-` of the first row of every layer with `G`.

Minecraft 1.16.5
Forge 36.2.34

kubejs-forge-1605.3.19-build.299.jar
compactcrafting-1.0.0.jar

**Comment by LindaJuffermans** [comment]
Actually the workaround only prevents the error. The multiblock doesn't craft with this recipe.

**Comment by MechOrigin** [comment]
Interesting 🤔 Kithi was testing this too. Seems the outside blocks like to have something there. We put plastic blocks along the outside and it worked fine after that. (could be any block)

**Comment by LindaJuffermans** [comment]
It looks to be stale from lack of response by the owners of this repo?

**Comment by robotgryphon** [comment]
Sorry, testing a new stale bot to help keep things active! Still looking to fix this before 1.18 closes, just caught up working with CM5 at the moment.

**Comment by robotgryphon** [comment]
Will be addressing before final close of 1.18 support - reopening

**Comment by robotgryphon** [comment]
Now in nightly testing for 1.18 and will be integrated into 1.19 shortly
