### ISSUE TITLE
[1.18.2] Field projectors don't return block

### ISSUE THREAD

**Issue by DelviousCrafts** [CompactMods/CompactCrafting#68]
Field projectors take forever to break and once broken do not drop the field projector item. This is true of any tool and with no tool at all.

Currently have a "dirty" fix for this by adding to the minable/pickaxe tag of Minecraft, but this does not solve the issue entirely as they do not drop the block inherently when broken with no tool like (I'm assuming) they should. 

Minecraft version: 1.18.2
Forge version: 40.1.84
Compact Crafting version: 2.0.0
Compact Machines version: 4.5.0

**Comment by nornagon** [comment]
It seems like these should be breakable & give the block back!

**Comment by adamico** [comment]
this affects all blocks (rescan, match proxies and field projector), is still valid for 1.19.2 and fixed by adding the correct tags to the blocks
