### ISSUE TITLE
[Feature Request] Extra Recipe Requirements (Entity support)

### ISSUE THREAD

**Issue by MuteTiefling** [CompactMods/CompactCrafting#7]
Thought it might be cool to have recipes that require mob entities inside it. 

As a basic example, you might make a cage of iron bars and drop a cow inside. Once compacted, you get a cow spawner.

**Comment by robotgryphon** [comment]
Definitely had this in my idea backlog; the only major problem I'm having is conceptualizing how the recipe layout would look. Separate entities list in the recipe? What about coordinates? Need to figure out a good representation of that in-config..

**Comment by MuteTiefling** [comment]
Separate entities list sounds good, yeah. As for coordinates, I'd suggest either it is limited to anywhere in the field, or possibly allow an offset to be defined from the center block. So Offset of 1 would mean the entity would have to be in the inner 3x3x3 area.

If people want to get really fancy with their mob placement requirements, they can always build the structure in such a way that a mob can only realistically go in one spot.

**Comment by robotgryphon** [comment]
Started putting more thought into this. I think I'll expand this idea out into a more generic "extra recipe requirement" feature, and entities will just be my test implementation. That way, whenever the recipe API gets implemented, I can just let people make their own recipe requirements. Will work the same way layers and their serializers work now.
