### ISSUE TITLE
mixed layer recipe help please? (noob)

### ISSUE THREAD

**Issue by wildfire2501** [CompactMods/CompactCrafting#70]
so i am starting to add recipe's instead of just editing and i started with the simplest.
which is a nonsense recipe for crafting 9 stone pickaxes (yep really its completely useless but funny)
it looks like this in kubejs: 

    event.recipes.compactcrafting.miniaturization({
    recipeSize: 3,
    layers: [
       {
        type: "compactcrafting:mixed",
        pattern: [
          ["_", "_", "_"],
          ["G", "G", "G"],
          ["_", "_", "_"],
         ],
       },
       {
        type: "compactcrafting:mixed",
        pattern: [
          ["_", "_", "_"],
          ["_", "W", "_"],
          ["_", "_", "_"],
         ],
       },
       {
        type: "compactcrafting:mixed",
        pattern: [
          ["_", "_", "_"],
          ["_", "W", "_"],
          ["_", "_", "_"],
         ],
       },
     ],

    catalyst: {
      id: "minecraft:ender_pearl",
      Count: 1,
     },

    components: {
      W: {
        type: "compactcrafting:block",
        block: "quark:stick_block",
       },
      G: {
        type: "compactcrafting:block",
        block: "quark:sturdy_stone",
       },
     },

    outputs: [
      {
        id: "minecraft:stone_pickaxe",
        Count: 9,
         },
       ],
     });

so ingame it doesnt give any errors and displays in jei as it should.
but once i place the blocks in the field and toss in the enderpearl nothing happens.
i have tried placing the "head" the other way but that doesnt work either.

so the question is really... what am i getting wrong ? or could it be an issue with the placement of the blocks ?
![New World (1)](https://github.com/CompactMods/CompactCrafting/assets/131200359/c710393e-c689-4c5c-ab2c-b58a1142b57c)

**Comment by Apceniy** [comment]
A screenshot of your setup would be helpful.

**Comment by wildfire2501** [comment]
> A screenshot of your setup would be helpful.

ive edited the original post to include a screenshot

**Comment by Apceniy** [comment]
the setup seems correct, can you check if the recipe is detected by using either a Match proxy or a mod like The One Probe?

**Comment by wildfire2501** [comment]
You can't see it very well but I have a match proxy linked to the projector on the right. It has never output a signal when trying this recipe
(I have checked my setup with a known recipe and confirmed that my match proxy works, I used the recipe for a copper tier compact machine)

I can try the one probe once I get home tomorrow.

**Comment by wildfire2501** [comment]
The one probe is telling me my field proxies are bound to the center space of the projected field.

Where should I look to see if the probe detects the recipe?

**Comment by Apceniy** [comment]
If you look at any of the 4 projectors, it should tell you the current recipe. If it doesn't, it doesn't recognize the recipe. Also, could you edit your initial message to properly put the recipe in the code block so the formatting won't be screwed up?

**Comment by wildfire2501** [comment]
![20230522_174206_HDR.jpg](https://github.com/CompactMods/CompactCrafting/assets/131200359/4edb7320-c818-440f-8db1-71aa9f63cbbc)

I fixed the formatting.
As you can see it doesn't list a recipe.

But I also doesn't list a recipe when I look at a projector that has an actual recipe in its field..  and the recipe works..
