### ISSUE TITLE
When Compact Crafting is installed, it causes Prefab to lag badly

### ISSUE THREAD

**Issue by aaronhowser1** [CompactMods/CompactCrafting#71]
Here's a spark profiler of me placing a structure from Prefab down while Compact Crafting is installed: https://spark.lucko.me/CJcZLzoQoY

![image](https://github.com/CompactMods/CompactCrafting/assets/15698722/7576821b-85c6-4ffb-bf3a-37907318974c)

Here's the same while CC is not: https://spark.lucko.me/SicatNZYT6

![image](https://github.com/CompactMods/CompactCrafting/assets/15698722/89a7268b-8768-4c27-87f0-d6adf3e51317)

This is using `compactcrafting-3.1.0.jar`

**Comment by aaronhowser1** [comment]
Apparently a potential fix to this would be using the Points of Interest mechanic, the thing used for villager work stations etc, rather than checking an 11x11x11 cube every time a block is placed. I don't know how it works, it was just mentioned to me.

**Comment by aaronhowser1** [comment]
pp

**Comment by DoubleHypercube** [comment]
FUCK STALE BOT
ITS BAD

from aaron with love

**Comment by eyecubed** [comment]
FUCK STALE BOT
ITS BAD

from aaron with love

**Comment by screret** [comment]
FUCK STALE BOT
ITS BAD

from aaron with love

**Comment by aaronhowser1** [comment]
yall no
