### ISSUE TITLE
JEI does not handle blockstates well

### ISSUE THREAD

**Issue by AlleCraft-alterego** [CompactMods/CompactCrafting#8]
all not full block (for exemple slab or redstone_wire) in datapack recipe don't rendered in image or ingredient in jei integration, but recipe work if used

**Comment by robotgryphon** [comment]
As an update: Still working on this; it appears to show up if you don't specify a specific blockstate in the recipe JSON (you'll need Properties, all of them must be set).

I'm trying to expand the system to take a set of required properties, so the recipe matcher can ignore non-critical props (like direction, or redstone connectivity). Stay tuned.

**Comment by AlleCraft-alterego** [comment]
oh, thanks !

**Comment by robotgryphon** [comment]
Going to keep this as an omnibus towards full JEI support; beta 1 adds some nice things to fix the recipe loader, but JEI won't show all the possible states right now.

**Comment by robotgryphon** [comment]
Closing this as the block component is reaching maturity. There will still be improvements but those will be noticed in commits/changelogs.

**Comment by AlleCraft-alterego** [comment]
wonderful !
